# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: nexus-api
    metrics_path: '/api/v1/monitoring/metrics'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.


    static_configs:
      #local - targets: ["api:8000"]
      - targets: ["nexus-api-ci20.onrender.com"]

  - job_name: nexus-workers
    scheme: https #production
    static_configs:
    #local - targets: ['worker-1:', 'worker-2:9101', 'worker-3:9101']
      - targets: ['nexus-worker-gqfe.onrender.com']

